/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accessibility: typeof import('./src/components/common/Accessibility.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CategoryProperties: typeof import('./src/components/common/CategoryProperties.vue')['default']
    copy: typeof import('./src/components/common/SizeTag copy.vue')['default']
    CustomizersComponents: typeof import('./src/components/common/CustomizersComponents.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    ModifiedValueDisplay: typeof import('./src/components/common/ModifiedValueDisplay.vue')['default']
    ModifierDisplay: typeof import('./src/components/common/ModifierDisplay.vue')['default']
    ModifiersDisplay: typeof import('./src/components/common/ModifiersDisplay.vue')['default']
    ModSettings: typeof import('./src/components/mod/ModSettings.vue')['default']
    ModUpdate: typeof import('./src/components/mod/ModUpdate.vue')['default']
    ProductionMethodSelector: typeof import('./src/components/common/ProductionMethodSelector.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ResearchTag: typeof import('./src/components/common/ResearchTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SizeTag: typeof import('./src/components/common/SizeTag.vue')['default']
    StateTag: typeof import('./src/components/common/StateTag.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TurretCard: typeof import('./src/components/turret/TurretCard.vue')['default']
    TurretCreate: typeof import('./src/components/turret/TurretCreate.vue')['default']
    TurretsSummary: typeof import('./src/components/turret/TurretsSummary.vue')['default']
    TurretUpdate: typeof import('./src/components/turret/TurretUpdate.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
